Specified two-column csv file
lbl-srg/funnel pull request #78
Opened 2024-03-27 21:54 UTC by JayHuLBL

This closes #76.

2024-04-03 13:53 UTC, mwetter approved these changes

2024-04-03 13:54 UTC, AntoineGautier requested changes
Please see my inline comments.

2024-04-03 13:54 UTC, AntoineGautier commented on pyfunnel/pyfunnel.py
> +            if (len(next(spamreader)) != 2):
I believe that if you use `next` here, the next iteration on the iterator (for loop below) starts at index 1 and not 0, i.e., the first row is skipped.
Why not test `len(spamreader[0])`? Or each line within the for loop: `len(row)`?

2024-04-03 13:54 UTC, AntoineGautier commented on pyfunnel/pyfunnel.py
> +                raise RuntimeError("The {} CSV file must have exactly two columns.".format(s))
Shouldn't this rather be an `IOError `?

2024-04-12 19:34 UTC, JayHuLBL commented
@AntoineGautier Please see the updated one.

2024-04-15 06:49 UTC, AntoineGautier commented
@JayHuLBL In 857ddda I propose to keep the iterable object (rather than casting it into a list which is potentially less memory-efficient) and check the length of each row. My thinking is that, if the CSV is corrupted with, e.g., an element missing at row 10000, the user will have better error information this way. If you want to revert back to checking only the first row, maybe keeping the iterable object and checking `len(list(spamreader)[0])` would be best.

2024-04-15 06:50 UTC, AntoineGautier approved these changes

2024-04-16 21:06 UTC, merged